### ISSUE TITLE
All other requests got into mockServiceWorker.

### ISSUE THREAD

**Issue by litan1106** [itaditya/msw-storybook-addon#19]
The service worker worked fine in localhost:6006 but not in Azure Static Web App.

I deployed a storybook with msw-addon to Azure Static Web App but all requests got into the service worker.

![image](https://user-images.githubusercontent.com/1310539/109880945-603dcc00-7c2c-11eb-85b4-d3d321e18390.png)

```
mockServiceWorker.js:265 [MSW] Failed to mock a "GET" request to "https://xxx.azurestaticapps.net/runtime~main.f1d0f47e5792ea375d40.bundle.js": TypeError: Cannot read property 'id' of undefined
    at handleRequest **(https://xxx.azurestaticapps.net/mockServiceWorker.js:117:34)**
```

**Comment by Je12emy** [comment]
I have the same problem in [Chromatic](https://www.chromatic.com/), I guess requests to localhost are being blocked by Chromatic, so it makes sense it won't work.
